name: Build Prerequisites

jobs:
  setup:
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust compilation prerequisites
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler
          rustup toolchain install stable --profile minimal --no-self-update
          rustup target add wasm32-unknown-unknown
          rustup component add rustfmt clippy --toolchain nightly

      - name: Rust Cache
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3
